export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',
  STOCK_NOT_AVAILABLE: 'STOCK_NOT_AVAILABLE',
  STOCK_INSUFFICIENT_CARATS: 'STOCK_INSUFFICIENT_CARATS',
  STOCK_ALREADY_ON_MEMO: 'STOCK_ALREADY_ON_MEMO',
  STOCK_ALREADY_ON_HOLD: 'STOCK_ALREADY_ON_HOLD',
  STOCK_BARCODE_NOT_FOUND: 'STOCK_BARCODE_NOT_FOUND',
  STOCK_NOT_IN_BRANCH: 'STOCK_NOT_IN_BRANCH',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  CREDIT_LIMIT_EXCEEDED: 'CREDIT_LIMIT_EXCEEDED',
  UNBALANCED_JOURNAL: 'UNBALANCED_JOURNAL',
  DUPLICATE_ENTITY: 'DUPLICATE_ENTITY',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
