packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '0': '@'
  '1': p
  '2': r
  '3': i
  '4': s
  '5': m
  '6': a
  '7': /
  '8': c
  '9': l
  '10': i
  '11': e
  '12': n
  '13': t
  '14': ','
  '15': p
  '16': r
  '17': i
  '18': s
  '19': m
  '20': a
  '21': ','
  '22': e
  '23': s
  '24': b
  '25': u
  '26': i
  '27': l
  '28': d
  '29': ','
  '30': s
  '31': h
  '32': a
  '33': r
  '34': p
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  msw: true
